### PR TITLE
Fix Telegram comments channel link

### PR DESCRIPTION
**Pull request by mykmykpet**

### CODE REVIEW

**Comment by igoradamenko** [comment]
But it does not work if user don't have Telegram on his device (for example they can use web-client), or if they use custom client.

**Comment by mykmykpet** [comment]
Таки не подумал.

**Comment by igoradamenko** [comment]
We can create proxy page for this (check this out: https://igoradamenko.com/blog/all/rkn-and-links-to-telegram/). But I'm not sure that it's a big problem for IT podcast. I mean, IT-guys should now everything about the RKN shit and can find Telegram channel without any problem.

If we really care about them, we can just add a note like this:

```html
<li>Комментарии в <a href="https://twitter.com/radiot_comments">Твитере</a> и в <a href="https://t.me/radiot_comments">Телеграме</a> (@radiot_comments)</li>
```

image

So if anyone can't click on the links, they can just find channel by name using in-app search.

/cc @umputun

**Comment by mykmykpet** [comment]
Прокси, лучше не делать, а то еще и сайт забанят, они умеют.

**Comment by mykmykpet** [comment]
@igoradamenko, как по мне, твоё решение получше будет.

**Pull request closed without merging**
